<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-PHF5J10" name="runner.RunCuke" tests="1" failures="0" timestamp="10 Sep 2019 09:25:59 GMT" time="43.379" errors="1">
  <testcase name="feature" time="43.379" classname="runner.RunCuke">
    <error type="java.lang.Throwable" message="Multiple failures (2):nnFailure 1 of 2:njunit.framework.ComparisonFailure: Both are same expected:&lt;[row 2 or column ASK A QUESTION does not exist in xls]&gt; but was:&lt;[Schedule Consultation]&gt;
	at junit.framework.Assert.assertEquals(Assert.java:100)
	at steps.AskAQuestionsAvailability.i_can_see_Schedule_Consulation(AskAQuestionsAvailability.java:33)
	at ✽.Then I can see Schedule Consulation.(src/test/resources/features/AskAQuestion.feature:5)
nnFailure 2 of 2:ncucumber.runtime.CucumberException: junit.framework.ComparisonFailure: Both are same expected:&lt;[row 2 or column ASK A QUESTION does not exist in xls]&gt; but was:&lt;[Schedule Consultation]&gt;">
      <![CDATA[java.lang.Throwable: Multiple failures (2):nnFailure 1 of 2:njunit.framework.ComparisonFailure: Both are same expected:<[row 2 or column ASK A QUESTION does not exist in xls]> but was:<[Schedule Consultation]>
	at junit.framework.Assert.assertEquals(Assert.java:100)
	at steps.AskAQuestionsAvailability.i_can_see_Schedule_Consulation(AskAQuestionsAvailability.java:33)
	at ✽.Then I can see Schedule Consulation.(src/test/resources/features/AskAQuestion.feature:5)
nnFailure 2 of 2:ncucumber.runtime.CucumberException: junit.framework.ComparisonFailure: Both are same expected:<[row 2 or column ASK A QUESTION does not exist in xls]> but was:<[Schedule Consultation]>
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- feature -->
</testsuite> <!-- runner.RunCuke -->
